### ISSUE TITLE
Cannot login or signup

### ISSUE THREAD

**Issue by yusefmosiah** [mjunaidca/cal-ai#1]
Hey, first off, let me commend you for making such a useful project open source.

I've been trying to get oauth working for my GPT for a few weeks now, and I haven't yet found the solution.

I tried deploying your project to Vercel, and it gives me this error when I try to register a new user account.

I'm a noob to next.js and vercel, and I thought maybe I got the database configuration messed up, but even after removing the DB and using txt file persistence, I get the same error.

I'd love some help debugging this.

Thanks,

Yusef

``` 
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11) {
  cause: _RequestContentLengthMismatchError: Request body length does not match content-length header
      at AsyncWriter.end (node:internal/deps/undici/undici:8829:19)
      at writeIterable (node:internal/deps/undici/undici:8737:16) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}
```

<img width="1409" alt="Screenshot 2024-01-22 at 3 57 14 PM" src="https://github.com/mjunaidca/caxgpt/assets/56694624/76b4c23e-bf7f-43f5-b8ec-58bbfc2069a1">

**Comment by mjunaidca** [comment]
Hey Yusef, 

The first step is to run the project locally and then comes vercel deployment and GPT integration. 

- Can you kindly confirm if the project is running perfectly on your machine?
- And have registered any account while running it locally?

Before running the project locally kindly ensure you have added following envirinment variables in your .env file.

```
DB_URL=neon_postgress_sql_url
SECRET_KEY=any_random_value
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=360
REFRESH_TOKEN_EXPIRE_MINUTES=10080

BACKEND_URL=http://localhost:3000
```

and then run the alembic migrations. The commands for it are present in readme.md

If you face issues while running it locally please share them. Else kindly deploy it on vercel and share if any error occurs.

**Comment by yusefmosiah** [comment]
Muhammad, 

Thanks for getting back to me.

Yes, I have it running locally just fine. But when I deploy to vercel, I always get the same error: 

```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11) {
  cause: _RequestContentLengthMismatchError: Request body length does not match content-length header
      at AsyncWriter.end (node:internal/deps/undici/undici:8829:19)
      at writeIterable (node:internal/deps/undici/undici:8737:16) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}
```

This was my .env for vercel:

```
# Created by Vercel CLI
ACCESS_TOKEN_EXPIRE_MINUTES="360"
ALGORITHM="HS256"
BACKEND_URL="https://caxgpt-lilac.vercel.app/"
DB_URL="postgresql://<redacted>:<redacted>@<redacted>.postgres.vercel-storage.com/verceldb"
NX_DAEMON=""
POSTGRES_DATABASE="verceldb"
POSTGRES_HOST="<redacted>.postgres.vercel-storage.com"
POSTGRES_PASSWORD="<redacted>"
POSTGRES_PRISMA_URL="postgres://<redacted>:<redacted>@<redacted>.postgres.vercel-storage.com/verceldb?pgbouncer=true&connect_timeout=15"
POSTGRES_URL="postgres://<redacted>:<redacted>@<redacted>.postgres.vercel-storage.com/verceldb"
POSTGRES_URL_NON_POOLING="postgres://<redacted>:<redacted>@<redacted>.postgres.vercel-storage.com/verceldb"
POSTGRES_USER=<redacted>
REFRESH_TOKEN_EXPIRE_MINUTES="10080"
SECRET_KEY=<redacted>
TURBO_REMOTE_ONLY=""
TURBO_RUN_SUMMARY=""
VERCEL="1"
VERCEL_ENV="production"
VERCEL_GIT_COMMIT_AUTHOR_LOGIN=""
VERCEL_GIT_COMMIT_AUTHOR_NAME=""
VERCEL_GIT_COMMIT_MESSAGE=""
VERCEL_GIT_COMMIT_REF=""
VERCEL_GIT_COMMIT_SHA=""
VERCEL_GIT_PREVIOUS_SHA=""
VERCEL_GIT_PROVIDER=""
VERCEL_GIT_PULL_REQUEST_ID=""
VERCEL_GIT_REPO_ID=""
VERCEL_GIT_REPO_OWNER=""
VERCEL_GIT_REPO_SLUG=""
VERCEL_URL=""
```

One thing that confuses me is why vercel configures the postgres urls as "postgres://" instead of "postgresql://"

Anyway, it wasn't working so I tried to use Neon postgres, and that, with this .env, still doesn't work:

```
# Created by Vercel CLI
ACCESS_TOKEN_EXPIRE_MINUTES="360"
ALGORITHM="HS256"
BACKEND_URL="https://caxgpt-lilac.vercel.app/"
DB_URL="postgresql://<redacted>:<redacted>@<redacted>.aws.neon.tech/cax?sslmode=require"
NX_DAEMON=""
REFRESH_TOKEN_EXPIRE_MINUTES="10080"
SECRET_KEY=<redacted>
TURBO_REMOTE_ONLY=""
TURBO_RUN_SUMMARY=""
VERCEL="1"
VERCEL_ENV="production"
VERCEL_GIT_COMMIT_AUTHOR_LOGIN=""
VERCEL_GIT_COMMIT_AUTHOR_NAME=""
VERCEL_GIT_COMMIT_MESSAGE=""
VERCEL_GIT_COMMIT_REF=""
VERCEL_GIT_COMMIT_SHA=""
VERCEL_GIT_PREVIOUS_SHA=""
VERCEL_GIT_PROVIDER=""
VERCEL_GIT_PULL_REQUEST_ID=""
VERCEL_GIT_REPO_ID=""
VERCEL_GIT_REPO_OWNER=""
VERCEL_GIT_REPO_SLUG=""
VERCEL_URL=""
```

**Comment by yusefmosiah** [comment]
It occurs to me that I'm not running the database migrations in prod.

How is that done with vercel?

**Comment by mjunaidca** [comment]
The problem is occurring due to **trailing slash** in this environment variable

- BACKEND_URL="https://caxgpt-lilac.vercel.app/"

It shall be without the trailing slash:

- **BACKEND_URL=https://caxgpt-lilac.vercel.app** 

The migrations are run once to create the tables in database. Kindly update the env variable in production and share if the problem still continues.

**Comment by yusefmosiah** [comment]
haha, so simple. thanks for your help and support.

I removed the trailing slash, and while that changed the error, it didn't solve it

Now I get a 500 status code.

<img width="1157" alt="Screenshot 2024-01-24 at 8 52 40 PM" src="https://github.com/mjunaidca/caxgpt/assets/56694624/76a0994e-7766-4416-89e7-65ccb8c9aab7">

**Comment by mjunaidca** [comment]
The Errors are abstracted on frontend. Now the database request is failing.

In your .env file the SECRET_KEY=<redacted> indicates that is is empty.

Have you setup SECRET_KEY variable value in vercel? It can be any random string like "secret" etc.

**Comment by yusefmosiah** [comment]
Yes, I have a SECRET_KEY set in vercel. I just didn't show it, i "redacted" it.

**Comment by mjunaidca** [comment]
What error does vercel log shows

**Comment by yusefmosiah** [comment]
<img width="2240" alt="Screenshot 2024-01-25 at 1 31 23 AM" src="https://github.com/mjunaidca/caxgpt/assets/56694624/3dcea973-cb2f-472e-a485-4dae8064c89b">

500 and 504

**Comment by mjunaidca** [comment]
Are you deploying the same cloned project or have modified it?

Kindly share the GitHub repo or minimum code to reproduce the current Error.

**Comment by yusefmosiah** [comment]
https://github.com/yusefmosiah/caxgpt

This is my fork. Thanks so much for the help.

**Comment by mjunaidca** [comment]
I have clone your fork - added my .env variables file and then

1. Ran the project locally
2. Deployed it on vercel and tested signup & login routes

Everything worked perfectly.

Based on your commits history it seems the issue is with database and probably alembic is misconfigured. 

Are the tables created in database?

**Comment by yusefmosiah** [comment]
I agree, it’s probably a database issue. 

How do I create the tables in the database?

**Comment by mjunaidca** [comment]
As in current fork nothing significant is done here's my recommendation:

1. Create a new Fork
2. In .env file add these env vars and replace DB_URL with your NEON Database url:

```
DB_URL=postgresql://calx-gpt-next?sslmode=require
SECRET_KEY=secret
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=360 # 6 hours
REFRESH_TOKEN_EXPIRE_MINUTES=10080 # 7 days
BACKEND_URL=https://abcd-roan.vercel.app
```

3. Open root folder in terminal and run these commands to run the migrations:
a. `alembic revision --autogenerate -m "Add Todos Table`
b. `alembic upgrade head`

Then open your database and confirm that the users and todos table is present there.

4. Now run the project locally and with env var `BACKEND_URL` =http://localhost:3000

If this step runs successfully then
5. link and deploy your projecy

**Comment by yusefmosiah** [comment]
ahhh, thank you! I just needed to run the migrations on the production DB.

Thank you so much Muhammad, for helping me with this.  OK, now that it's running I can get down to actually handling oauth with ChatGPT, and then customizing this project to make it fulfill my requirements.
